name: AWS Ansible Workflow

on:
    workflow_dispatch:
    push:

jobs:
    ansible-deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Caching
              id: cache-step
              uses: actions/cache@v3
              with:
                  path: |
                      ~/.cache
                      ~/.ansible
                      /usr/local/lib/python3.10.12/dist-packages
                  key: ansible-project-deps
            - name: Install Ansible Latest
              if: steps.cache-step.outputs.cache-hit != 'true'
              shell: pwsh
              run: |
                  pip3 install ansible boto3
            - name: Install the ansible galaxy collection
              if: steps.cache-step.outputs.cache-hit != 'true'
              shell: pwsh
              run: |
                  ansible-galaxy collection install amazon.aws
            - name: Authenticate To AWS
              uses: aws-actions/configure-aws-credentials@v4
              with:
                  aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                  aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                  aws-region: us-east-1
            - name: Clone the code
              uses: actions/checkout@v4
            - name: Run Ansible Inventory Command
              shell: pwsh
              run: |
                ansible-inventory --inventory my_inventory.aws_ec2.yml -list